### ISSUE TITLE
direct url to download rock960 image

### ISSUE THREAD

**Issue by Nelson-numerical-software** [jveitchmichaelis/rock960_docker_build#1]
your docker is very great :)
But I am more interested by direct image
Where can we find .img (buster) to flash directly on rock960 with etcher ?

**Comment by jveitchmichaelis** [comment]
When you run the build script, you should end up with a folder that contains system.img. You can flash that to the rock960 or (I think) an SD card as well.

Have a look in the release section of the repository for a pre built img https://github.com/jveitchmichaelis/rock960_docker_build/releases

(under assets, eg https://github.com/jveitchmichaelis/rock960_docker_build/releases/download/buster_base_v1/buster_base.tar.gz)

**Comment by jveitchmichaelis** [comment]
@Nelson-numerical-software did you manage to get the image working OK?

**Comment by Nelson-numerical-software** [comment]
> @Nelson-numerical-software did you manage to get the image working OK?

i got it thanks
